CREATE TABLE CUSTOMER (
    CUSTOMER_ID INT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(255),
    CUSTOMER_ADDRESS VARCHAR(255),
    CITY VARCHAR(255),
    POSTAL_CODE VARCHAR(10)
);

CREATE TABLE ORDERT (
    ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE TABLE PRODUCT (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_DESCRIPTION VARCHAR(255),
    PRODUCT_FINISH VARCHAR(255),
    STANDARD_PRICE DECIMAL(10,2)
);

CREATE TABLE ORDER_LINE (
    ORDER_ID INT,
    PRODUCT_ID INT,
    ORDER_QUANTITY INT,
    PRIMARY KEY (ORDER_ID, PRODUCT_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERT(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID)
);
